platform :ios, '12.0'

target 'SampleApp' do
  use_frameworks!

  pod 'NuguClientKitExternal', :path => '../'
  pod 'NuguUIKitExternal', :path => '../'
  pod 'NuguLoginKit', :path => '../'
  pod 'TycheSDK', :path => '../'
  pod 'JadeMarbleExternal', :path => '../'
  pod 'KeenSense', :path => '../'
  pod 'NuguAgentsExternal', :path => '../'
  pod 'NuguCore', :path => '../'
  pod 'NuguUtils', :path => '../'
  pod 'NuguObjcUtils', :path => '../'
  pod 'NuguServiceKit', :path => '../'
  pod 'OpusSDK', :path => '../'
  pod 'SilverTray', :path => '../'
end
